graphs:
  call_avg_number:
    time_frames:
      - day
      - month
      - week
    directory: call_avg_number
    source: all
    config: call_avg_number
  drops_by_channel:
    time_frames:
      - day
      - month
      - week
    directory: drops_by_channel
    source: all
    config: drops_channel
  num_open_calls:
    time_frames:
      - day
      - month
      - week
    directory: num_open_calls
    source: all
    config: num_open_calls
directory: graphs
