graphs:
  call_avg_number:
    script: draw_graph_call_avg_num.rb
    time_frames:
      - day
      - month
      - week
    directory: call_avg_number
    source: "vgw001.chi.full.0"
    config: call_avg_number
  drops_by_channel:
    script: draw_graph_drops_channel.rb
    time_frames:
      - day
      - month
      - week
    directory: drops_by_channel
    source: all
    config: drops_channel
  num_open_calls:
    script: draw_graph_num_open_calls.rb
    time_frames:
      - day
      - month
      - week
    directory: num_open_calls
    source: all
    config: num_open_calls
directory: graphs
